[package]
name = "g8rowfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
fmt = "0.1.0"
systemstat = "0.2.3"
time = "0.3.20"
wmi = "0.12.0"
